# INSTRUCTION:
# Build image (from the directory containing dockerfile):
# docker build -f dockerfile --tag 'ubuntu-g4:22.04-11.1.3-plgrid' .
# Run container:
# docker run -ti --rm ubuntu-g4:22.04-11.1.3-plgrid /bin/bash

FROM ubuntu:22.04
RUN echo 'APT::Install-Suggests "0";' >> /etc/apt/apt.conf.d/00-docker
RUN echo 'APT::Install-Recommends "0";' >> /etc/apt/apt.conf.d/00-docker

ARG JPET_G4_BRANCH=develop-agh
ARG JPET_FRAMEWORK_BRANCH=modular
ARG JPET_FRAMEWORK_EXAMPLE_BRANCH=modular4

RUN DEBIAN_FRONTEND=noninteractive && \
  apt-get update && \
  apt-get install -y gpg && \
  apt-get install -y cmake && \
  apt-get install -y git && \
  apt-get install -y wget && \
  apt-get install -y curl && \
  apt-get install -y zlib1g-dev && \
  apt-get install -y ca-certificates && \
  wget --no-check-certificate https://repo.anaconda.com/miniconda/Miniconda3-py310_23.9.0-0-Linux-x86_64.sh -O /opt/miniconda.sh && \
  /bin/bash /opt/miniconda.sh -b -p /opt/conda; \
  rm /opt/miniconda.sh

ENV CONDA_DIR=/opt/conda
ENV PATH=$CONDA_DIR/bin:$PATH

RUN conda config --add channels defaults && conda config --add channels conda-forge && conda update -n base conda && conda install -n base conda-libmamba-solver && conda config --set solver libmamba

# Fetch the latest commit SHA for the branch to force re-cloning if there's a change
RUN cd /opt/ && \
    JPET_G4_COMMIT=$(git ls-remote https://github.com/JPETTomography/J-PET-geant4.git $JPET_G4_BRANCH | awk '{print $1}') && \
    echo $JPET_G4_COMMIT && \
    git clone --single-branch --branch $JPET_G4_BRANCH https://github.com/JPETTomography/J-PET-geant4.git

RUN conda init && \
    /bin/bash && \ 
    conda env create --name jpet -f /opt/J-PET-geant4/setups/conda_env_g4v11-jpet.yml

RUN conda activate jpet && cd /opt/J-PET-geant4 && /bin/bash setups/init_submodules.sh \
    mkdir build && cd build && cmake ../ -DMT=ON; make -j2

# RUN cd /opt/geant4-data && \
#     wget --no-check-certificate https://cern.ch/geant4-data/datasets/G4NDL.4.7.tar.gz; tar -xzvf G4NDL.4.7.tar.gz; rm G4NDL.4.7.tar.gz && \
#     wget --no-check-certificate https://cern.ch/geant4-data/datasets/G4EMLOW.8.5.tar.gz; tar -xzvf G4EMLOW.8.5.tar.gz; rm G4EMLOW.8.5.tar.gz && \
#     wget --no-check-certificate https://cern.ch/geant4-data/datasets/G4PhotonEvaporation.5.7.tar.gz; tar -xzvf G4PhotonEvaporation.5.7.tar.gz; rm G4PhotonEvaporation.5.7.tar.gz&& \
#     wget --no-check-certificate https://cern.ch/geant4-data/datasets/G4RadioactiveDecay.5.6.tar.gz; tar -xzvf G4RadioactiveDecay.5.6.tar.gz; rm G4RadioactiveDecay.5.6.tar.gz && \
#     wget --no-check-certificate https://cern.ch/geant4-data/datasets/G4PARTICLEXS.4.0.tar.gz; tar -xzvf G4PARTICLEXS.4.0.tar.gz; rm G4PARTICLEXS.4.0.tar.gz && \
#     wget --no-check-certificate https://cern.ch/geant4-data/datasets/G4PII.1.3.tar.gz; tar -xzvf G4PII.1.3.tar.gz; rm G4PII.1.3.tar.gz && \
#     wget --no-check-certificate https://cern.ch/geant4-data/datasets/G4RealSurface.2.2.tar.gz; tar -xzvf G4RealSurface.2.2.tar.gz; rm G4RealSurface.2.2.tar.gz && \
#     wget --no-check-certificate https://cern.ch/geant4-data/datasets/G4SAIDDATA.2.0.tar.gz; tar -xzvf G4SAIDDATA.2.0.tar.gz; rm G4SAIDDATA.2.0.tar.gz && \
#     wget --no-check-certificate https://cern.ch/geant4-data/datasets/G4ABLA.3.3.tar.gz; tar -xzvf G4ABLA.3.3.tar.gz; rm G4ABLA.3.3.tar.gz && \
#     wget --no-check-certificate https://cern.ch/geant4-data/datasets/G4ENSDFSTATE.2.3.tar.gz; tar -xzvf G4ENSDFSTATE.2.3.tar.gz; rm G4ENSDFSTATE.2.3.tar.gz


# RUN . /opt/conda/etc/profile.d/conda.sh && \
#     conda activate geant4 && \
#     cd /opt/ && git clone --single-branch --branch develop-agh https://github.com/JPETTomography/J-PET-geant4.git && \
#     cd J-PET-geant4 && /bin/bash setups/init_submodules.sh && \
#     mkdir build && cd build && cmake ../ -DMT=ON; make -j2