# INSTRUCTION:
# Build image (from the directory containing dockerfile):
# docker build -f dockerfile --tag 'ubuntu-g4:22.04-11.1.3-plgrid' .
# Run container:
# docker run -ti --rm ubuntu-g4:22.04-11.1.3-plgrid /bin/bash

FROM ubuntu:22.04
RUN echo 'APT::Install-Suggests "0";' >> /etc/apt/apt.conf.d/00-docker
RUN echo 'APT::Install-Recommends "0";' >> /etc/apt/apt.conf.d/00-docker

ARG JPET_G4_BRANCH=develop-agh
ARG JPET_G4_REPO=https://github.com/JPETTomography/J-PET-geant4.git

ARG JPET_FRAMEWORK_BRANCH=modular5
ARG JPET_FRAMEWORK_REPO=https://github.com/kkacprzak/j-pet-framework.git

ARG JPET_FRAMEWORK_EXAMPLES_BRANCH=modular5
ARG JPET_FRAMEWORK_EXAMPLES_REPO=https://github.com/kkacprzak/j-pet-framework-examples.git

RUN DEBIAN_FRONTEND=noninteractive && \
  apt-get update && \
  apt-get install -y gpg && \
  apt-get install -y cmake && \
  apt-get install -y git && \
  apt-get install -y wget && \
  apt-get install -y curl && \
  apt-get install -y zlib1g-dev && \
  apt-get install -y ca-certificates && \
  wget --no-check-certificate https://repo.anaconda.com/miniconda/Miniconda3-py310_23.9.0-0-Linux-x86_64.sh -O /opt/miniconda.sh && \
  /bin/bash /opt/miniconda.sh -b -p /opt/conda; \
  rm /opt/miniconda.sh

ENV CONDA_DIR=/opt/conda
ENV PATH=$CONDA_DIR/bin:$PATH

# ----------------------------------------
# J-PET-geant4
# ----------------------------------------
SHELL ["/bin/bash", "-c"]
RUN conda init && /bin/bash && cd /opt/ && \
  git clone --single-branch --branch $JPET_G4_BRANCH $JPET_G4_REPO && \
  conda env create --name jpet -f /opt/J-PET-geant4/setups/conda_env_g4v11-jpet.yml && \
  source /opt/conda/etc/profile.d/conda.sh && conda activate jpet && cd /opt/J-PET-geant4 && /bin/bash setups/init_submodules.sh && \
  mkdir build && cd build && cmake ../ -DMT=ON; make -j2

# ----------------------------------------
# J-PET-Framework
# ----------------------------------------
SHELL ["/bin/bash", "-c"]
RUN conda init && /bin/bash && cd /opt/ && \
  git clone --single-branch --branch $JPET_FRAMEWORK_BRANCH $JPET_FRAMEWORK_REPO && \
  cd j-pet-framework/ && git submodule init && git submodule update && \
  source /opt/conda/etc/profile.d/conda.sh && conda activate jpet && \
  cd /opt/ && mkdir framework-build && mkdir framework-install && cd framework-build && \
  cmake -DCMAKE_INSTALL_PREFIX=../framework-install ../j-pet-framework/ && make -j2 && make install && \
  source /opt/framework-install/bin/thisframework.sh

# ----------------------------------------
# J-PET-Framework Examples
# ----------------------------------------
SHELL ["/bin/bash", "-c"]
RUN conda init && /bin/bash && cd /opt/ && \
  git clone --single-branch --branch $JPET_FRAMEWORK_EXAMPLES_BRANCH $JPET_FRAMEWORK_EXAMPLES_REPO && \
  source /opt/conda/etc/profile.d/conda.sh && conda activate jpet && \
  source /opt/framework-install/bin/thisframework.sh && \
  cd /opt/ && mkdir examples-build && cd examples-build && \
  cmake /opt/j-pet-framework-examples/ && make -j2