# INSTRUCTION:
# Build image (from the directory containing dockerfile):
# docker build -f dockerfile --tag 'ubuntu-g4:22.04-11.1.3-plgrid' .
# Run container:
# docker run -ti --rm ubuntu-g4:22.04-11.1.3-plgrid /bin/bash

FROM ubuntu:22.04
RUN echo 'APT::Install-Suggests "0";' >> /etc/apt/apt.conf.d/00-docker
RUN echo 'APT::Install-Recommends "0";' >> /etc/apt/apt.conf.d/00-docker

ARG JPET_G4_BRANCH=develop-agh
ARG JPET_FRAMEWORK_BRANCH=modular
ARG JPET_FRAMEWORK_EXAMPLE_BRANCH=modular4

RUN DEBIAN_FRONTEND=noninteractive && \
  apt-get update && \
  apt-get install -y gpg && \
  apt-get install -y cmake && \
  apt-get install -y git && \
  apt-get install -y wget && \
  apt-get install -y curl && \
  apt-get install -y zlib1g-dev && \
  apt-get install -y ca-certificates && \
  wget --no-check-certificate https://repo.anaconda.com/miniconda/Miniconda3-py310_23.9.0-0-Linux-x86_64.sh -O /opt/miniconda.sh && \
  /bin/bash /opt/miniconda.sh -b -p /opt/conda; \
  rm /opt/miniconda.sh

ENV CONDA_DIR=/opt/conda
ENV PATH=$CONDA_DIR/bin:$PATH

# ----------------------------------------
# J-PET-geant4
# ----------------------------------------
SHELL ["/bin/bash", "-c"]
RUN conda init && /bin/bash && cd /opt/ && \
    git clone --single-branch --branch $JPET_G4_BRANCH https://github.com/JPETTomography/J-PET-geant4.git && \
    conda env create --name jpet -f /opt/J-PET-geant4/setups/conda_env_g4v11-jpet.yml && \
    source /opt/conda/etc/profile.d/conda.sh && conda activate jpet && cd /opt/J-PET-geant4 && /bin/bash setups/init_submodules.sh && \
    mkdir build && cd build && cmake ../ -DMT=ON; make -j2